version: "3.8"

services:
  backend:
    build:
      context: ./backend         # the backend folder
      dockerfile: Dockerfile     # the file you just moved
    container_name: backend
    ports:
      - "8002:8002"
    env_file:
      - backend/.env             # optional environment variables
    # If you want them to share a network, no config needed by default

  frontend:
    build:
      context: ./frontend        # the frontend folder
      dockerfile: Dockerfile     # the new Dockerfile for Next/React
    container_name: frontend
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    # depends_on:
    #   - backend
    # environment:
    #   - REACT_APP_API_URL=http://backend:8002   # example if you want to talk to 'backend' container
